In [4]:
import scipy

print(scipy.__version__)

1.5.2


In [5]:
from scipy import constants

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [7]:
print(constants.yotta)
print(constants.zetta)
print(constants.exa)
print(constants.peta)
print(constants.tera)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.pico)
print(constants.femto)
print(constants.atto)
print(constants.zepto)



1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [8]:
print(constants.gram)
print(constants.metric_ton)
print(constants.grain)
print(constants.lb)
print(constants.pound)
print(constants.oz)
print(constants.ounce)
print(constants.stone)
print(constants.long_ton)
print(constants.short_ton)
print(constants.troy_ounce)
print(constants.troy_pound)
print(constants.carat)
print(constants.atomic_mass)
print(constants.m_u)
print(constants.u)

0.001
1000.0
6.479891e-05
0.45359236999999997
0.45359236999999997
0.028349523124999998
0.028349523124999998
6.3502931799999995
1016.0469088
907.1847399999999
0.031103476799999998
0.37324172159999996
0.0002
1.6605390666e-27
1.6605390666e-27
1.6605390666e-27


In [9]:
print(constants.degree)
print(constants.arcmin)
print(constants.arcminute)
print(constants.arcsec)
print(constants.arcsecond)

0.017453292519943295
0.0002908882086657216
0.0002908882086657216
4.84813681109536e-06
4.84813681109536e-06


In [10]:
print(constants.inch)
print(constants.foot)
print(constants.yard)
print(constants.mile)
print(constants.mil)
print(constants.pt)
print(constants.point)
print(constants.survey_foot)
print(constants.survey_mile)
print(constants.nautical_mile)
print(constants.fermi)
print(constants.angstrom)
print(constants.micron)
print(constants.au)
print(constants.astronomical_unit)
print(constants.light_year)
print(constants.parsec)






0.0254
0.30479999999999996
0.9143999999999999
1609.3439999999998
2.5399999999999997e-05
0.00035277777777777776
0.00035277777777777776
0.3048006096012192
1609.3472186944373
1852.0
1e-15
1e-10
1e-06
149597870700.0
149597870700.0
9460730472580800.0
3.085677581491367e+16


In [11]:
print(constants.kmh)
print(constants.mph)
print(constants.mach)
print(constants.speed_of_sound)
print(constants.knot)

0.2777777777777778
0.44703999999999994
340.5
340.5
0.5144444444444445


In [12]:
from scipy.optimize import root 
from math import cos

def eqn(x):
    return x+cos(x)
myroot=root(eqn,0)
print(myroot.x)

[-0.73908513]


In [13]:
myroot

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])

In [14]:
myroot.x

array([-0.73908513])

In [15]:
eqn(2)

1.5838531634528576

In [17]:
import numpy as np 
from scipy.sparse.csgraph import connected_components 
from scipy.sparse import csr_matrix 

arr=np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

newarr= csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0]))


In [18]:
newarr

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 4 stored elements in Compressed Sparse Row format>

In [19]:
from scipy.sparse.csgraph import dijkstra 
from scipy.sparse import csr_matrix 

arr=np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

newarr=csr_matrix(arr)

print(dijkstra(newarr,return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


In [20]:
newarr

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 4 stored elements in Compressed Sparse Row format>

In [21]:
graph=[
    [0,1,2,0],
    [0,0,0,1],
    [0,0,0,3],
    [0,0,0,0]
    ]
graph=csr_matrix(graph)
print(graph)

  (0, 1)	1
  (0, 2)	2
  (1, 3)	1
  (2, 3)	3


In [22]:
dist_matrix,predecessors=dijkstra(csgraph=graph,directed=False,indices=0,return_predecessors=True)

In [23]:
dist_matrix

array([0., 1., 2., 2.])

In [24]:
predecessors

array([-9999,     0,     0,     1])

In [25]:
from scipy import io

arr=np.array([0,1,2,3,4,5,6,7,8,9])

#export

io.savemat('arr.mat',{"vec":arr})

#import

mydata=io.loadmat('arr.mat')

print(mydata)


{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Sep 15 11:53:04 2021', '__version__': '1.0', '__globals__': [], 'vec': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}


In [26]:
mydata

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Sep 15 11:53:04 2021',
 '__version__': '1.0',
 '__globals__': [],
 'vec': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}

In [46]:
from scipy.interpolate import interp1d


xs=np.arange(10)

ys=2*xs+1 

inter_func=interp1d(xs,ys)

newarr=inter_func(np.arange(5,7,0.1))

print(newarr)

[11.  11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6
 13.8 14.  14.2 14.4 14.6 14.8]


In [30]:
xs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ys

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
inter_func

In [33]:
newarr

array([5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

In [47]:
x=np.arange(0,10)

y=np.exp(-x/3.0)

f=interp1d(x,y)

In [48]:
f

In [49]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
y

array([1.        , 0.71653131, 0.51341712, 0.36787944, 0.26359714,
       0.1888756 , 0.13533528, 0.09697197, 0.06948345, 0.04978707])

In [51]:
xnew=np.arange(0,9,0.1)

ynew=f(xnew)

In [52]:
ynew

array([1.        , 0.97165313, 0.94330626, 0.91495939, 0.88661252,
       0.85826566, 0.82991879, 0.80157192, 0.77322505, 0.74487818,
       0.71653131, 0.69621989, 0.67590847, 0.65559705, 0.63528563,
       0.61497421, 0.5946628 , 0.57435138, 0.55403996, 0.53372854,
       0.51341712, 0.49886335, 0.48430958, 0.46975582, 0.45520205,
       0.44064828, 0.42609451, 0.41154074, 0.39698698, 0.38243321,
       0.36787944, 0.35745121, 0.34702298, 0.33659475, 0.32616652,
       0.31573829, 0.30531006, 0.29488183, 0.2844536 , 0.27402537,
       0.26359714, 0.25612498, 0.24865283, 0.24118068, 0.23370852,
       0.22623637, 0.21876422, 0.21129206, 0.20381991, 0.19634776,
       0.1888756 , 0.18352157, 0.17816754, 0.17281351, 0.16745947,
       0.16210544, 0.15675141, 0.15139738, 0.14604335, 0.14068932,
       0.13533528, 0.13149895, 0.12766262, 0.12382629, 0.11998996,
       0.11615363, 0.11231729, 0.10848096, 0.10464463, 0.1008083 ,
       0.09697197, 0.09422312, 0.09147426, 0.08872541, 0.08597